/* do not change this file, it is auto generated by storybook. */

import "@storybook/addon-ondevice-controls/register"
import "@storybook/addon-ondevice-actions/register"

import { argsEnhancers } from "@storybook/addon-actions/dist/preview"
import { decorators, parameters } from "./preview"

// stories
import * as Button from "../../../packages/native/src/components/Button.stories"
import * as Card from "../../../packages/native/src/components/Card.stories"
import * as Input from "../../../packages/native/src/components/Input.stories"
import * as Badge from "../../../packages/native/src/components/Badge.stories"
import * as Avatar from "../../../packages/native/src/components/Avatar.stories"
import * as Switch from "../../../packages/native/src/components/Switch.stories"
import * as Checkbox from "../../../packages/native/src/components/Checkbox.stories"
import * as Toast from "../../../packages/native/src/components/Toast.stories"
import * as Alert from "../../../packages/native/src/components/Alert.stories"
import * as Progress from "../../../packages/native/src/components/Progress.stories"
import * as Spinner from "../../../packages/native/src/components/Spinner.stories"
import * as Radio from "../../../packages/native/src/components/Radio.stories"
import * as Slider from "../../../packages/native/src/components/Slider.stories"
import * as Separator from "../../../packages/native/src/components/Separator.stories"
import * as Skeleton from "../../../packages/native/src/components/Skeleton.stories"
import * as TextArea from "../../../packages/native/src/components/TextArea.stories"
import * as BackButton from "../../../packages/native/src/components/BackButton.stories"
import * as BottomSheet from "../../../packages/native/src/components/BottomSheet.stories"
import * as ActionSheet from "../../../packages/native/src/components/ActionSheet.stories"
import * as BottomTabBar from "../../../packages/native/src/components/BottomTabBar.stories"
import * as SafeAreaView from "../../../packages/native/src/components/SafeAreaView.stories"
import * as ScrollView from "../../../packages/native/src/components/ScrollView.stories"

const getStories = () => {
  return {
    "./Button.stories": Button,
    "./Card.stories": Card,
    "./Input.stories": Input,
    "./Badge.stories": Badge,
    "./Avatar.stories": Avatar,
    "./Switch.stories": Switch,
    "./Checkbox.stories": Checkbox,
    "./Toast.stories": Toast,
    "./Alert.stories": Alert,
    "./Progress.stories": Progress,
    "./Spinner.stories": Spinner,
    "./Radio.stories": Radio,
    "./Slider.stories": Slider,
    "./Separator.stories": Separator,
    "./Skeleton.stories": Skeleton,
    "./TextArea.stories": TextArea,
    "./BackButton.stories": BackButton,
    "./BottomSheet.stories": BottomSheet,
    "./ActionSheet.stories": ActionSheet,
    "./BottomTabBar.stories": BottomTabBar,
    "./SafeAreaView.stories": SafeAreaView,
    "./ScrollView.stories": ScrollView,
  }
}

export { decorators, parameters, getStories, argsEnhancers }
