import type {
  PrimitiveTokens,
  Scale,
  ScaleName,
  ScaleStepValue,
  SemanticMap,
  TokenRef,
} from '../types.js';

const SCALE_STEPS: ScaleStepValue[] = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

function resolveHex(ref: TokenRef, primitives: PrimitiveTokens): string {
  if (ref === 'white') return '#ffffff';
  if (ref === 'black') return '#000000';
  const [scaleName, stepStr] = ref.split('.') as [ScaleName, string];
  const step = Number(stepStr) as ScaleStepValue;
  return primitives[scaleName]![step].hex;
}

function scaleToW3C(name: string, scale: Scale): Record<string, unknown> {
  const group: Record<string, unknown> = {};
  for (const step of SCALE_STEPS) {
    const entry = scale[step];
    group[String(step)] = {
      $type: 'color',
      $value: entry.hex,
      $extensions: {
        'com.ragnar': {
          oklch: { l: entry.oklch.l, c: entry.oklch.c, h: entry.oklch.h },
        },
      },
    };
  }
  return group;
}

export function compilePrimitivesJSON(primitives: PrimitiveTokens): string {
  const doc: Record<string, unknown> = {};
  for (const [name, scale] of Object.entries(primitives)) {
    if (scale) {
      doc[name] = scaleToW3C(name, scale);
    }
  }
  return JSON.stringify(doc, null, 2);
}

export function compileSemanticJSON(
  map: SemanticMap,
  primitives: PrimitiveTokens
): string {
  const doc: Record<string, unknown> = {};
  for (const [token, entry] of Object.entries(map)) {
    doc[token] = {
      $type: 'color',
      light: {
        $value: resolveHex(entry.light, primitives),
        $ref: entry.light,
      },
      dark: {
        $value: resolveHex(entry.dark, primitives),
        $ref: entry.dark,
      },
      role: entry.role,
      ...(entry.contrastAgainst ? { contrastAgainst: entry.contrastAgainst } : {}),
      ...(entry.minContrast ? { minContrast: entry.minContrast } : {}),
    };
  }
  return JSON.stringify(doc, null, 2);
}

function compilePrimitiveCSSBlock(
  scaleName: string,
  scale: Scale,
  prefix: string
): string {
  const lines: string[] = [];
  for (const step of SCALE_STEPS) {
    const entry = scale[step];
    lines.push(`  --color-${prefix}-${step}: ${entry.hex};`);
  }
  return lines.join('\n');
}

export function compilePrimitivesCSS(
  primitives: PrimitiveTokens,
  themeName: string
): string {
  const blocks: string[] = [];

  for (const [name, scale] of Object.entries(primitives)) {
    if (!scale) continue;
    blocks.push(`\n  /* ${name} */`);
    blocks.push(compilePrimitiveCSSBlock(name, scale, name));
  }

  return `/* Generated by ragnar-theme-generator — ${themeName} primitives */\n\n[data-theme="${themeName}"] {\n${blocks.join('\n')}\n}`;
}

function compileModeCSSBlock(
  map: SemanticMap,
  primitives: PrimitiveTokens,
  mode: 'light' | 'dark',
  scaleName: ScaleName,
  cssPrefix: string
): string {
  const scale = primitives[scaleName];
  if (!scale) return '';

  const lines: string[] = [];
  const ref = mode === 'light' ? 'light' : 'dark';

  const mainStep: ScaleStepValue = mode === 'light' ? 500 : 400;
  const bgStep: ScaleStepValue = mode === 'light' ? 50 : 950;
  const tintStep: ScaleStepValue = mode === 'light' ? 100 : 900;
  const fgStep: ScaleStepValue = mode === 'light' ? 700 : 200;
  const shadeStep: ScaleStepValue = mode === 'light' ? 800 : 300;

  lines.push(`  --${cssPrefix}-main: ${scale[mainStep].hex};`);
  lines.push(`  --${cssPrefix}-background: ${scale[bgStep].hex};`);
  lines.push(`  --${cssPrefix}-tint: ${scale[tintStep].hex};`);
  lines.push(`  --${cssPrefix}-foreground: ${scale[fgStep].hex};`);
  lines.push(`  --${cssPrefix}-shade: ${scale[shadeStep].hex};`);

  return lines.join('\n');
}

export function compileModeCSS(
  map: SemanticMap,
  primitives: PrimitiveTokens,
  mode: 'light' | 'dark',
  themeName: string
): string {
  const lines: string[] = [];
  const neutral = primitives.neutral;
  if (!neutral) throw new Error('Neutral scale is required');

  const bgSteps: Record<string, ScaleStepValue> = mode === 'light'
    ? { primary: 50, secondary: 100, tertiary: 200, quaternary: 300, quinary: 400 }
    : { primary: 800, secondary: 900, tertiary: 950, quaternary: 700, quinary: 600 };

  const fgSteps: Record<string, ScaleStepValue> = mode === 'light'
    ? { primary: 950, secondary: 800, tertiary: 600, quaternary: 500, quinary: 400 }
    : { primary: 50, secondary: 100, tertiary: 200, quaternary: 300, quinary: 400 };

  lines.push(`  /* Backgrounds */`);
  for (const [level, step] of Object.entries(bgSteps)) {
    lines.push(`  --backgrounds-${level}: ${neutral[step].hex};`);
  }

  lines.push(`\n  /* Foregrounds */`);
  for (const [level, step] of Object.entries(fgSteps)) {
    lines.push(`  --foregrounds-${level}: ${neutral[step].hex};`);
  }

  const paletteScales: [ScaleName, string][] = [
    ['primary', 'accent'],
    ['error', 'error'],
    ['warning', 'warning'],
    ['success', 'success'],
    ['info', 'info'],
  ];

  for (const [scaleName, cssPrefix] of paletteScales) {
    const block = compileModeCSSBlock(map, primitives, mode, scaleName, cssPrefix);
    if (block) {
      lines.push(`\n  /* ${cssPrefix} */`);
      lines.push(block);
    }
  }

  const modeLabel = mode === 'light' ? 'Light' : 'Dark';
  return `/* Generated by ragnar-theme-generator — ${themeName} ${mode} mode */\n\n[data-theme="${themeName}"][data-mode="${mode}"],\n[data-theme="${themeName}"][data-mode="${modeLabel}"] {\n${lines.join('\n')}\n}`;
}

export function compileThemeCSS(
  map: SemanticMap,
  primitives: PrimitiveTokens,
  themeName: string,
  inputHash: string
): string {
  const lines: string[] = [];

  lines.push(`/* Generated by ragnar-theme-generator v0.1.0 */`);
  lines.push(`/* Input hash: ${inputHash} */`);
  lines.push(`/* Theme: ${themeName} */`);
  lines.push('');

  const lightLines: string[] = [];
  const darkLines: string[] = [];

  for (const [token, entry] of Object.entries(map)) {
    const lightHex = resolveHex(entry.light, primitives);
    const darkHex = resolveHex(entry.dark, primitives);

    lightLines.push(`  --${token}: ${lightHex}; /* ${entry.light} */`);
    darkLines.push(`  --${token}: ${darkHex}; /* ${entry.dark} */`);
  }

  lines.push(`[data-theme="${themeName}"][data-mode="light"],`);
  lines.push(`[data-theme="${themeName}"][data-mode="Light"] {`);
  lines.push(lightLines.join('\n'));
  lines.push('}');
  lines.push('');
  lines.push(`[data-theme="${themeName}"][data-mode="dark"],`);
  lines.push(`[data-theme="${themeName}"][data-mode="Dark"] {`);
  lines.push(darkLines.join('\n'));
  lines.push('}');

  return lines.join('\n');
}

export function compileCreateThemeTokens(
  map: SemanticMap,
  primitives: PrimitiveTokens,
  mode: 'light' | 'dark'
): Record<string, string> {
  const tokens: Record<string, string> = {};
  for (const [token, entry] of Object.entries(map)) {
    const ref = mode === 'light' ? entry.light : entry.dark;
    tokens[`--${token}`] = resolveHex(ref, primitives);
  }
  return tokens;
}
