import type { Meta, StoryObj } from "@storybook/react";
import { Skeleton } from "./Skeleton";
declare const meta: Meta<typeof Skeleton>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Variants: Story;
export declare const CustomSizes: Story;
export declare const CustomRadius: Story;
export declare const NoAnimation: Story;
export declare const TextSkeleton: Story;
export declare const AvatarSkeleton: Story;
export declare const CardSkeleton: Story;
export declare const ListItemSkeleton: Story;
export declare const ListItemVariants: Story;
export declare const SkeletonGroups: Story;
export declare const ProfileSkeleton: Story;
export declare const DashboardSkeleton: Story;
export declare const FeedSkeleton: Story;
//# sourceMappingURL=Skeleton.stories.d.ts.map