export interface ShaderUniforms {
    [key: string]: {
        value: number | number[] | Float32Array;
        type?: "float" | "vec2" | "vec3" | "vec4" | "mat4";
    };
}
export interface ShaderConfig {
    /** Fragment shader GLSL code */
    fragmentShader: string;
    /** Vertex shader GLSL code (optional, uses default) */
    vertexShader?: string;
    /** Uniform values */
    uniforms?: ShaderUniforms;
}
export interface BaseShaderProps {
    /** Animation speed multiplier */
    speed?: number;
    /** Mouse interaction */
    interactive?: boolean;
    /** Effect intensity (0-1) */
    intensity?: number;
    /** Primary colors */
    colors?: string[];
    /** Whether the shader is paused */
    paused?: boolean;
    /** Pixel ratio (default: window.devicePixelRatio) */
    pixelRatio?: number;
    /** Quality preset */
    quality?: "low" | "medium" | "high";
    /** Callback when shader is ready */
    onReady?: () => void;
    /** Callback on each frame */
    onFrame?: (time: number) => void;
}
export declare const VERTEX_SHADER_DEFAULT = "\n  attribute vec2 uv;\n  attribute vec2 position;\n  varying vec2 vUv;\n  void main() {\n    vUv = uv;\n    gl_Position = vec4(position, 0, 1);\n  }\n";
export declare const FRAGMENT_SHADER_GRADIENT = "\n  precision highp float;\n\n  uniform float uTime;\n  uniform vec2 uResolution;\n  uniform vec2 uMouse;\n  uniform float uIntensity;\n  uniform vec3 uColor1;\n  uniform vec3 uColor2;\n  uniform vec3 uColor3;\n\n  varying vec2 vUv;\n\n  void main() {\n    vec2 uv = vUv;\n\n    // Animated gradient\n    float t = uTime * 0.3;\n    float noise = sin(uv.x * 3.0 + t) * sin(uv.y * 3.0 + t) * 0.5 + 0.5;\n\n    vec3 color = mix(uColor1, uColor2, uv.x + sin(t) * 0.2);\n    color = mix(color, uColor3, uv.y + cos(t) * 0.2);\n    color = mix(color, uColor1, noise * uIntensity);\n\n    gl_FragColor = vec4(color, 1.0);\n  }\n";
export declare const FRAGMENT_SHADER_AURORA = "\n  precision highp float;\n\n  uniform float uTime;\n  uniform vec2 uResolution;\n  uniform vec2 uMouse;\n  uniform float uIntensity;\n  uniform vec3 uColor1;\n  uniform vec3 uColor2;\n  uniform vec3 uColor3;\n\n  varying vec2 vUv;\n\n  // Simplex noise function\n  vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }\n  vec2 mod289(vec2 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }\n  vec3 permute(vec3 x) { return mod289(((x*34.0)+1.0)*x); }\n\n  float snoise(vec2 v) {\n    const vec4 C = vec4(0.211324865405187, 0.366025403784439, -0.577350269189626, 0.024390243902439);\n    vec2 i  = floor(v + dot(v, C.yy));\n    vec2 x0 = v - i + dot(i, C.xx);\n    vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);\n    vec4 x12 = x0.xyxy + C.xxzz;\n    x12.xy -= i1;\n    i = mod289(i);\n    vec3 p = permute(permute(i.y + vec3(0.0, i1.y, 1.0)) + i.x + vec3(0.0, i1.x, 1.0));\n    vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);\n    m = m*m;\n    m = m*m;\n    vec3 x = 2.0 * fract(p * C.www) - 1.0;\n    vec3 h = abs(x) - 0.5;\n    vec3 ox = floor(x + 0.5);\n    vec3 a0 = x - ox;\n    m *= 1.79284291400159 - 0.85373472095314 * (a0*a0 + h*h);\n    vec3 g;\n    g.x = a0.x * x0.x + h.x * x0.y;\n    g.yz = a0.yz * x12.xz + h.yz * x12.yw;\n    return 130.0 * dot(m, g);\n  }\n\n  void main() {\n    vec2 uv = vUv;\n    float t = uTime * 0.2;\n\n    // Multiple layers of noise for aurora effect\n    float n1 = snoise(vec2(uv.x * 2.0, uv.y * 0.5 + t));\n    float n2 = snoise(vec2(uv.x * 4.0 + t * 0.5, uv.y * 1.0));\n    float n3 = snoise(vec2(uv.x * 1.0, uv.y * 2.0 - t * 0.3));\n\n    float aurora = (n1 + n2 * 0.5 + n3 * 0.25) * 0.5 + 0.5;\n    aurora = pow(aurora, 2.0) * uIntensity;\n\n    // Vertical fade\n    float fade = smoothstep(0.0, 0.6, uv.y) * smoothstep(1.0, 0.4, uv.y);\n    aurora *= fade;\n\n    // Color mixing\n    vec3 color = mix(uColor1, uColor2, aurora);\n    color = mix(color, uColor3, pow(aurora, 2.0));\n\n    // Add glow\n    color += uColor2 * aurora * 0.5;\n\n    gl_FragColor = vec4(color, aurora * 0.8 + 0.2);\n  }\n";
export declare const FRAGMENT_SHADER_BLOB = "\n  precision highp float;\n\n  uniform float uTime;\n  uniform vec2 uResolution;\n  uniform vec2 uMouse;\n  uniform float uIntensity;\n  uniform vec3 uColor1;\n  uniform vec3 uColor2;\n  uniform vec3 uColor3;\n\n  varying vec2 vUv;\n\n  float sdCircle(vec2 p, float r) {\n    return length(p) - r;\n  }\n\n  void main() {\n    vec2 uv = vUv * 2.0 - 1.0;\n    uv.x *= uResolution.x / uResolution.y;\n\n    float t = uTime * 0.5;\n\n    // Morphing blob\n    float blob = 0.0;\n    for (int i = 0; i < 5; i++) {\n      float fi = float(i);\n      vec2 offset = vec2(\n        sin(t + fi * 1.2) * 0.3,\n        cos(t + fi * 0.8) * 0.3\n      );\n      float size = 0.3 + sin(t + fi) * 0.1;\n      blob += smoothstep(size, size - 0.1, length(uv - offset));\n    }\n\n    blob = clamp(blob, 0.0, 1.0) * uIntensity;\n\n    // Color gradient\n    vec3 color = mix(uColor1, uColor2, blob);\n    color = mix(color, uColor3, pow(blob, 2.0));\n\n    gl_FragColor = vec4(color, blob);\n  }\n";
export declare const FRAGMENT_SHADER_NOISE = "\n  precision highp float;\n\n  uniform float uTime;\n  uniform vec2 uResolution;\n  uniform float uIntensity;\n  uniform vec3 uColor1;\n\n  varying vec2 vUv;\n\n  float random(vec2 st) {\n    return fract(sin(dot(st.xy, vec2(12.9898, 78.233))) * 43758.5453123);\n  }\n\n  void main() {\n    vec2 uv = vUv;\n\n    // Animated noise\n    float noise = random(uv + uTime * 0.1);\n    noise = mix(0.5, noise, uIntensity);\n\n    vec3 color = uColor1 * noise;\n\n    gl_FragColor = vec4(color, uIntensity * 0.5);\n  }\n";
export declare const FRAGMENT_SHADER_WAVE = "\n  precision highp float;\n\n  uniform float uTime;\n  uniform vec2 uResolution;\n  uniform vec2 uMouse;\n  uniform float uIntensity;\n  uniform vec3 uColor1;\n  uniform vec3 uColor2;\n\n  varying vec2 vUv;\n\n  void main() {\n    vec2 uv = vUv;\n    float t = uTime * 0.5;\n\n    // Wave distortion\n    float wave1 = sin(uv.x * 10.0 + t) * 0.1;\n    float wave2 = sin(uv.x * 5.0 - t * 0.5) * 0.15;\n    float wave3 = cos(uv.x * 15.0 + t * 0.7) * 0.05;\n\n    float y = uv.y + (wave1 + wave2 + wave3) * uIntensity;\n\n    // Gradient with waves\n    vec3 color = mix(uColor1, uColor2, smoothstep(0.3, 0.7, y));\n\n    gl_FragColor = vec4(color, 1.0);\n  }\n";
export declare const FRAGMENT_SHADER_MESH_GRADIENT = "\n  precision highp float;\n\n  uniform float uTime;\n  uniform vec2 uResolution;\n  uniform vec2 uMouse;\n  uniform float uIntensity;\n  uniform vec3 uColor1;\n  uniform vec3 uColor2;\n  uniform vec3 uColor3;\n  uniform vec3 uColor4;\n\n  varying vec2 vUv;\n\n  // Simplex noise\n  vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }\n  vec2 mod289(vec2 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }\n  vec3 permute(vec3 x) { return mod289(((x*34.0)+1.0)*x); }\n\n  float snoise(vec2 v) {\n    const vec4 C = vec4(0.211324865405187, 0.366025403784439, -0.577350269189626, 0.024390243902439);\n    vec2 i  = floor(v + dot(v, C.yy));\n    vec2 x0 = v - i + dot(i, C.xx);\n    vec2 i1 = (x0.x > x0.y) ? vec2(1.0, 0.0) : vec2(0.0, 1.0);\n    vec4 x12 = x0.xyxy + C.xxzz;\n    x12.xy -= i1;\n    i = mod289(i);\n    vec3 p = permute(permute(i.y + vec3(0.0, i1.y, 1.0)) + i.x + vec3(0.0, i1.x, 1.0));\n    vec3 m = max(0.5 - vec3(dot(x0,x0), dot(x12.xy,x12.xy), dot(x12.zw,x12.zw)), 0.0);\n    m = m*m;\n    m = m*m;\n    vec3 x = 2.0 * fract(p * C.www) - 1.0;\n    vec3 h = abs(x) - 0.5;\n    vec3 ox = floor(x + 0.5);\n    vec3 a0 = x - ox;\n    m *= 1.79284291400159 - 0.85373472095314 * (a0*a0 + h*h);\n    vec3 g;\n    g.x = a0.x * x0.x + h.x * x0.y;\n    g.yz = a0.yz * x12.xz + h.yz * x12.yw;\n    return 130.0 * dot(m, g);\n  }\n\n  void main() {\n    vec2 uv = vUv;\n    float t = uTime * 0.15;\n\n    // Animated mesh gradient using noise\n    float n1 = snoise(uv * 2.0 + t) * 0.5 + 0.5;\n    float n2 = snoise(uv * 3.0 - t * 0.5) * 0.5 + 0.5;\n    float n3 = snoise(uv * 1.5 + vec2(t, -t)) * 0.5 + 0.5;\n\n    // Four-corner gradient with noise displacement\n    vec3 tl = uColor1;\n    vec3 tr = uColor2;\n    vec3 bl = uColor3;\n    vec3 br = uColor4;\n\n    vec2 nuv = uv + vec2(n1 - 0.5, n2 - 0.5) * 0.2 * uIntensity;\n    nuv = clamp(nuv, 0.0, 1.0);\n\n    vec3 top = mix(tl, tr, nuv.x);\n    vec3 bottom = mix(bl, br, nuv.x);\n    vec3 color = mix(bottom, top, nuv.y);\n\n    // Add subtle glow\n    color += (uColor1 + uColor2) * 0.1 * n3 * uIntensity;\n\n    gl_FragColor = vec4(color, 1.0);\n  }\n";
export declare const FRAGMENT_SHADER_PARTICLES = "\n  precision highp float;\n\n  uniform float uTime;\n  uniform vec2 uResolution;\n  uniform float uIntensity;\n  uniform vec3 uColor1;\n  uniform vec3 uColor2;\n\n  varying vec2 vUv;\n\n  float random(vec2 st) {\n    return fract(sin(dot(st.xy, vec2(12.9898, 78.233))) * 43758.5453123);\n  }\n\n  void main() {\n    vec2 uv = vUv;\n    float t = uTime * 0.2;\n\n    vec3 color = vec3(0.0);\n\n    // Multiple particle layers\n    for (int i = 0; i < 3; i++) {\n      float fi = float(i);\n      vec2 grid = uv * (20.0 + fi * 10.0);\n      vec2 id = floor(grid);\n      vec2 gv = fract(grid) - 0.5;\n\n      float n = random(id + fi);\n      float size = n * 0.3 + 0.1;\n\n      // Animated position\n      vec2 offset = vec2(\n        sin(t + n * 6.28) * 0.2,\n        cos(t * 0.7 + n * 6.28) * 0.3 - t * 0.5\n      );\n      offset.y = mod(offset.y, 1.0) - 0.5;\n\n      float d = length(gv - offset);\n      float particle = smoothstep(size, size - 0.05, d);\n\n      vec3 pColor = mix(uColor1, uColor2, n);\n      color += pColor * particle * (1.0 - fi * 0.2);\n    }\n\n    color *= uIntensity;\n\n    gl_FragColor = vec4(color, length(color) * 0.5);\n  }\n";
export declare function hexToVec3(hex: string): [number, number, number];
export type ShaderPreset = "gradient" | "aurora" | "blob" | "noise" | "wave" | "mesh" | "particles";
export declare const SHADER_PRESETS: Record<ShaderPreset, string>;
export declare const PRESET_COLORS: Record<ShaderPreset, string[]>;
