import type { SemanticMap } from '../types.js';

export function buildSemanticMap(): SemanticMap {
  return {
    // ── Container ──────────────────────────────────────────────
    'container-bg':             { light: 'neutral.50',   dark: 'neutral.800',  role: 'bg' },
    'container-bg-alt':         { light: 'neutral.100',  dark: 'neutral.900',  role: 'bg' },
    'container-bg-inverse':     { light: 'neutral.800',  dark: 'neutral.100',  role: 'bg' },
    'container-border':         { light: 'neutral.200',  dark: 'neutral.700',  role: 'border' },
    'container-border-alt':     { light: 'neutral.300',  dark: 'neutral.600',  role: 'border' },
    'container-border-inverse': { light: 'neutral.600',  dark: 'neutral.200',  role: 'border' },
    'container-fg':             { light: 'neutral.950',  dark: 'neutral.50',   role: 'fg', contrastAgainst: 'container-bg', minContrast: 4.5 },
    'container-fg-alt':         { light: 'neutral.800',  dark: 'neutral.100',  role: 'fg', contrastAgainst: 'container-bg', minContrast: 4.5 },
    'container-fg-inverse':     { light: 'neutral.50',   dark: 'neutral.950',  role: 'fg', contrastAgainst: 'container-bg-inverse', minContrast: 4.5 },
    // Tooltip surface — matches container-bg in light and container-border in
    // dark, so the tooltip's border disappears against its own background.
    'tooltip-bg':               { light: 'neutral.50',   dark: 'neutral.700',  role: 'bg' },

    // ── Interactive ────────────────────────────────────────────
    'interactive-bg':           { light: 'neutral.50',   dark: 'neutral.800',  role: 'bg' },
    'interactive-bg-alt':       { light: 'neutral.100',  dark: 'neutral.900',  role: 'bg' },
    'interactive-bg-alt2':      { light: 'primary.50',   dark: 'primary.950',  role: 'bg' },
    'interactive-bg-disabled':  { light: 'neutral.200',  dark: 'neutral.700',  role: 'bg' },
    'interactive-bg-hover':     { light: 'neutral.200',  dark: 'neutral.700',  role: 'bg' },
    'interactive-bg-active':    { light: 'primary.800',  dark: 'primary.300',  role: 'bg' },
    'interactive-bg-selected':  { light: 'primary.800',  dark: 'primary.300',  role: 'bg' },
    'interactive-bg-inverse':   { light: 'neutral.950',  dark: 'neutral.50',   role: 'bg' },
    'interactive-border':       { light: 'neutral.200',  dark: 'neutral.700',  role: 'border' },
    'interactive-border-alt':   { light: 'neutral.300',  dark: 'neutral.600',  role: 'border' },
    'interactive-border-disabled': { light: 'neutral.300', dark: 'neutral.600', role: 'border' },
    'interactive-fg':           { light: 'neutral.950',  dark: 'neutral.50',   role: 'fg', contrastAgainst: 'interactive-bg', minContrast: 4.5 },
    // Secondary text targets the WCAG 3:1 large-text/UI tier; allowBelowDefault
    // keeps it there even when the config asks for a stricter floor (e.g. AAA).
    'interactive-fg-alt':       { light: 'neutral.600',  dark: 'neutral.300',  role: 'fg', contrastAgainst: 'interactive-bg', minContrast: 3.0, allowBelowDefault: true },
    'interactive-fg-readonly':  { light: 'neutral.800',  dark: 'neutral.100',  role: 'fg', contrastAgainst: 'interactive-bg', minContrast: 4.5 },
    'interactive-fg-disabled':  { light: 'neutral.400',  dark: 'neutral.500',  role: 'fg' },
    'interactive-fg-active':    { light: 'primary.100',  dark: 'primary.900',  role: 'fg', contrastAgainst: 'interactive-bg-active', minContrast: 4.5 },
    'interactive-fg-selected':  { light: 'primary.100',  dark: 'primary.900',  role: 'fg', contrastAgainst: 'interactive-bg-selected', minContrast: 4.5 },
    'interactive-fg-inverse':   { light: 'neutral.50',   dark: 'neutral.950',  role: 'fg', contrastAgainst: 'interactive-bg-inverse', minContrast: 4.5 },

    // ── Action Primary ─────────────────────────────────────────
    'action-primary-bg':          { light: 'primary.500', dark: 'primary.500',  role: 'bg' },
    'action-primary-bg-hover':    { light: 'primary.800', dark: 'primary.400',  role: 'bg' },
    'action-primary-bg-active':   { light: 'primary.800', dark: 'primary.400',  role: 'bg' },
    'action-primary-bg-selected': { light: 'primary.800', dark: 'primary.400',  role: 'bg' },
    'action-primary-bg-disabled': { light: 'primary.100', dark: 'primary.900',  role: 'bg' },
    'action-primary-bg-inverse':  { light: 'primary.50',  dark: 'primary.950',  role: 'bg' },
    'action-primary-fg':          { light: 'neutral.50',  dark: 'neutral.50',   role: 'fg', contrastAgainst: 'action-primary-bg', minContrast: 4.5 },
    'action-primary-fg-disabled': { light: 'neutral.400', dark: 'neutral.600',  role: 'fg' },
    'action-primary-fg-active':   { light: 'neutral.50',  dark: 'neutral.50',   role: 'fg', contrastAgainst: 'action-primary-bg-active', minContrast: 4.5 },
    'action-primary-fg-selected': { light: 'neutral.50',  dark: 'neutral.50',   role: 'fg', contrastAgainst: 'action-primary-bg-selected', minContrast: 4.5 },
    'action-primary-fg-inverse':  { light: 'primary.700', dark: 'primary.200',  role: 'fg', contrastAgainst: 'action-primary-bg-inverse', minContrast: 4.5 },

    // ── Action Secondary ───────────────────────────────────────
    'action-secondary-bg-hover':     { light: 'primary.100', dark: 'primary.900', role: 'bg' },
    'action-secondary-bg-active':    { light: 'primary.500', dark: 'primary.500', role: 'bg' },
    'action-secondary-bg-selected':  { light: 'primary.500', dark: 'primary.500', role: 'bg' },
    'action-secondary-bg-disabled':  { light: 'neutral.200', dark: 'neutral.700', role: 'bg' },
    'action-secondary-border':       { light: 'primary.500', dark: 'primary.400', role: 'border' },
    'action-secondary-border-alt':   { light: 'primary.800', dark: 'primary.300', role: 'border' },
    'action-secondary-border-disabled': { light: 'primary.100', dark: 'primary.900', role: 'border' },
    'action-secondary-border-inverse':  { light: 'primary.50',  dark: 'primary.950', role: 'border' },
    'action-secondary-fg':           { light: 'primary.500', dark: 'primary.400', role: 'fg', contrastAgainst: 'container-bg', minContrast: 4.5 },
    'action-secondary-fg-alt':       { light: 'neutral.950', dark: 'neutral.50',  role: 'fg' },
    'action-secondary-fg-disabled':  { light: 'neutral.400', dark: 'neutral.500', role: 'fg' },
    'action-secondary-fg-active':    { light: 'neutral.50',  dark: 'neutral.50',  role: 'fg', contrastAgainst: 'action-secondary-bg-active', minContrast: 4.5 },
    'action-secondary-fg-selected':  { light: 'neutral.50',  dark: 'neutral.50',  role: 'fg', contrastAgainst: 'action-secondary-bg-selected', minContrast: 4.5 },
    'action-secondary-fg-inverse':   { light: 'neutral.950', dark: 'neutral.50',  role: 'fg' },

    // ── Action Tertiary ────────────────────────────────────────
    'action-tertiary-bg':            { light: 'neutral.50',   dark: 'neutral.800', role: 'bg' },
    'action-tertiary-bg-alt':        { light: 'neutral.100',  dark: 'neutral.900', role: 'bg' },
    'action-tertiary-bg-hover':      { light: 'primary.50',   dark: 'primary.950', role: 'bg' },
    'action-tertiary-bg-active':     { light: 'primary.100',  dark: 'primary.900', role: 'bg' },
    'action-tertiary-bg-selected':   { light: 'primary.100',  dark: 'primary.900', role: 'bg' },
    'action-tertiary-bg-disabled':   { light: 'neutral.50',   dark: 'neutral.800', role: 'bg' },
    'action-tertiary-bg-inverse':    { light: 'neutral.50',   dark: 'neutral.800', role: 'bg' },
    'action-tertiary-border':        { light: 'primary.500',  dark: 'primary.400', role: 'border' },
    'action-tertiary-border-alt':    { light: 'primary.800',  dark: 'primary.300', role: 'border' },
    'action-tertiary-border-disabled': { light: 'neutral.300', dark: 'neutral.600', role: 'border' },
    'action-tertiary-border-inverse':  { light: 'primary.100', dark: 'primary.900', role: 'border' },
    'action-tertiary-fg':            { light: 'primary.500',  dark: 'primary.400', role: 'fg', contrastAgainst: 'action-tertiary-bg', minContrast: 4.5 },
    'action-tertiary-fg-alt':        { light: 'neutral.950',  dark: 'neutral.50',  role: 'fg' },
    'action-tertiary-fg-disabled':   { light: 'neutral.400',  dark: 'neutral.500', role: 'fg' },
    'action-tertiary-fg-active':     { light: 'primary.700',  dark: 'primary.200', role: 'fg', contrastAgainst: 'action-tertiary-bg-active', minContrast: 4.5 },
    'action-tertiary-fg-selected':   { light: 'primary.700',  dark: 'primary.200', role: 'fg', contrastAgainst: 'action-tertiary-bg-selected', minContrast: 4.5 },
    'action-tertiary-fg-inverse':    { light: 'neutral.50',   dark: 'neutral.950', role: 'fg' },

    // ── Destructive ────────────────────────────────────────────
    'destructive-bg':           { light: 'error.50',  dark: 'error.950', role: 'bg' },
    'destructive-bg-alt':       { light: 'error.100', dark: 'error.900', role: 'bg' },
    'destructive-bg-hover':     { light: 'error.100', dark: 'error.900', role: 'bg' },
    'destructive-bg-active':    { light: 'error.800', dark: 'error.300', role: 'bg' },
    'destructive-bg-selected':  { light: 'error.800', dark: 'error.300', role: 'bg' },
    'destructive-bg-disabled':  { light: 'neutral.200', dark: 'neutral.700', role: 'bg' },
    'destructive-bg-inverse':   { light: 'error.800', dark: 'error.200', role: 'bg' },
    'destructive-border':       { light: 'error.500', dark: 'error.400', role: 'border' },
    'destructive-border-alt':   { light: 'error.800', dark: 'error.300', role: 'border' },
    'destructive-border-disabled': { light: 'error.100', dark: 'error.900', role: 'border' },
    'destructive-border-inverse':  { light: 'error.50',  dark: 'error.950', role: 'border' },
    'destructive-fg':           { light: 'error.700', dark: 'error.200', role: 'fg', contrastAgainst: 'destructive-bg', minContrast: 4.5 },
    'destructive-fg-alt':       { light: 'neutral.950', dark: 'neutral.50', role: 'fg' },
    'destructive-fg-disabled':  { light: 'neutral.400', dark: 'neutral.500', role: 'fg' },
    'destructive-fg-active':    { light: 'neutral.50',  dark: 'neutral.950', role: 'fg', contrastAgainst: 'destructive-bg-active', minContrast: 4.5 },
    'destructive-fg-selected':  { light: 'neutral.50',  dark: 'neutral.950', role: 'fg', contrastAgainst: 'destructive-bg-selected', minContrast: 4.5 },
    'destructive-fg-inverse':   { light: 'error.50',    dark: 'error.950',   role: 'fg', contrastAgainst: 'destructive-bg-inverse', minContrast: 4.5 },

    // ── Positive ───────────────────────────────────────────────
    'positive-bg':             { light: 'success.50',  dark: 'success.950', role: 'bg' },
    'positive-bg-alt':         { light: 'success.100', dark: 'success.900', role: 'bg' },
    'positive-bg-inverse':     { light: 'success.800', dark: 'success.200', role: 'bg' },
    'positive-border':         { light: 'success.500', dark: 'success.400', role: 'border' },
    'positive-border-alt':     { light: 'success.800', dark: 'success.300', role: 'border' },
    'positive-border-inverse': { light: 'success.50',  dark: 'success.950', role: 'border' },
    'positive-fg':             { light: 'success.700', dark: 'success.200', role: 'fg', contrastAgainst: 'positive-bg', minContrast: 4.5 },
    'positive-fg-alt':         { light: 'neutral.950', dark: 'neutral.50',  role: 'fg' },
    'positive-fg-inverse':     { light: 'success.50',  dark: 'success.950', role: 'fg', contrastAgainst: 'positive-bg-inverse', minContrast: 4.5 },

    // ── Cautionary ─────────────────────────────────────────────
    'cautionary-bg':             { light: 'warning.50',  dark: 'warning.950', role: 'bg' },
    'cautionary-bg-alt':         { light: 'warning.100', dark: 'warning.900', role: 'bg' },
    'cautionary-bg-inverse':     { light: 'warning.800', dark: 'warning.200', role: 'bg' },
    'cautionary-border':         { light: 'warning.500', dark: 'warning.400', role: 'border' },
    'cautionary-border-alt':     { light: 'warning.800', dark: 'warning.300', role: 'border' },
    'cautionary-border-inverse': { light: 'warning.50',  dark: 'warning.950', role: 'border' },
    'cautionary-fg':             { light: 'warning.700', dark: 'warning.200', role: 'fg', contrastAgainst: 'cautionary-bg', minContrast: 4.5 },
    'cautionary-fg-alt':         { light: 'neutral.950', dark: 'neutral.50',  role: 'fg' },
    'cautionary-fg-inverse':     { light: 'warning.50',  dark: 'warning.950', role: 'fg', contrastAgainst: 'cautionary-bg-inverse', minContrast: 4.5 },

    // ── Informative ────────────────────────────────────────────
    'informative-bg':             { light: 'info.50',  dark: 'info.950', role: 'bg' },
    'informative-bg-alt':         { light: 'info.100', dark: 'info.900', role: 'bg' },
    'informative-bg-inverse':     { light: 'info.800', dark: 'info.200', role: 'bg' },
    'informative-border':         { light: 'info.500', dark: 'info.400', role: 'border' },
    'informative-border-alt':     { light: 'info.800', dark: 'info.300', role: 'border' },
    'informative-border-inverse': { light: 'info.50',  dark: 'info.950', role: 'border' },
    'informative-fg':             { light: 'info.700', dark: 'info.200', role: 'fg', contrastAgainst: 'informative-bg', minContrast: 4.5 },
    'informative-fg-alt':         { light: 'neutral.950', dark: 'neutral.50', role: 'fg' },
    'informative-fg-inverse':     { light: 'info.50',  dark: 'info.950', role: 'fg', contrastAgainst: 'informative-bg-inverse', minContrast: 4.5 },

    // ── Important ──────────────────────────────────────────────
    'important-bg':             { light: 'primary.50',  dark: 'primary.950', role: 'bg' },
    'important-bg-alt':         { light: 'primary.100', dark: 'primary.900', role: 'bg' },
    'important-bg-inverse':     { light: 'primary.800', dark: 'primary.200', role: 'bg' },
    'important-border':         { light: 'primary.500', dark: 'primary.400', role: 'border' },
    'important-border-alt':     { light: 'primary.800', dark: 'primary.300', role: 'border' },
    'important-border-inverse': { light: 'primary.50',  dark: 'primary.950', role: 'border' },
    'important-fg':             { light: 'primary.700', dark: 'primary.200', role: 'fg', contrastAgainst: 'important-bg', minContrast: 4.5 },
    'important-fg-alt':         { light: 'neutral.950', dark: 'neutral.50',  role: 'fg' },
    'important-fg-inverse':     { light: 'primary.50',  dark: 'primary.950', role: 'fg', contrastAgainst: 'important-bg-inverse', minContrast: 4.5 },

    // ── Dataviz ────────────────────────────────────────────────
    'dataviz-1-main':  { light: 'primary.500', dark: 'primary.400', role: 'decorative' },
    'dataviz-1-tint':  { light: 'primary.100', dark: 'primary.900', role: 'decorative' },
    'dataviz-1-shade': { light: 'primary.800', dark: 'primary.200', role: 'decorative' },
    'dataviz-2-main':  { light: 'info.500',    dark: 'info.400',    role: 'decorative' },
    'dataviz-2-tint':  { light: 'info.100',    dark: 'info.900',    role: 'decorative' },
    'dataviz-2-shade': { light: 'info.800',    dark: 'info.200',    role: 'decorative' },
    'dataviz-3-main':  { light: 'success.500', dark: 'success.400', role: 'decorative' },
    'dataviz-3-tint':  { light: 'success.100', dark: 'success.900', role: 'decorative' },
    'dataviz-3-shade': { light: 'success.800', dark: 'success.200', role: 'decorative' },
    'dataviz-4-main':  { light: 'primary.600', dark: 'primary.300', role: 'decorative' },
    'dataviz-4-tint':  { light: 'primary.200', dark: 'primary.800', role: 'decorative' },
    'dataviz-4-shade': { light: 'primary.900', dark: 'primary.100', role: 'decorative' },
    'dataviz-5-main':  { light: 'warning.500', dark: 'warning.400', role: 'decorative' },
    'dataviz-5-tint':  { light: 'warning.100', dark: 'warning.900', role: 'decorative' },
    'dataviz-5-shade': { light: 'warning.800', dark: 'warning.200', role: 'decorative' },
    'dataviz-6-main':  { light: 'error.500',   dark: 'error.400',   role: 'decorative' },
    'dataviz-6-tint':  { light: 'error.100',   dark: 'error.900',   role: 'decorative' },
    'dataviz-6-shade': { light: 'error.800',   dark: 'error.200',   role: 'decorative' },
    'dataviz-7-main':  { light: 'success.600', dark: 'success.300', role: 'decorative' },
    'dataviz-7-tint':  { light: 'success.200', dark: 'success.800', role: 'decorative' },
    'dataviz-7-shade': { light: 'success.900', dark: 'success.100', role: 'decorative' },
    'dataviz-8-main':  { light: 'info.600',    dark: 'info.300',    role: 'decorative' },
    'dataviz-8-tint':  { light: 'info.200',    dark: 'info.800',    role: 'decorative' },
    'dataviz-8-shade': { light: 'info.900',    dark: 'info.100',    role: 'decorative' },
  };
}
