import type { PrimitiveTokens, ScaleName, ScaleStepValue, SemanticMap, TokenRef } from '../types.js';
import { checkContrast } from '../tokens/contrast.js';

const SCALE_STEPS: ScaleStepValue[] = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

function resolveHex(ref: TokenRef, primitives: PrimitiveTokens): string {
  if (ref === 'white') return '#ffffff';
  if (ref === 'black') return '#000000';
  const [scaleName, stepStr] = ref.split('.') as [ScaleName, string];
  const step = Number(stepStr) as ScaleStepValue;
  const scale = primitives[scaleName];
  if (!scale) {
    throw new Error(`Invalid token reference "${ref}": unknown scale "${scaleName}".`);
  }
  const entry = scale[step];
  if (!entry) {
    throw new Error(`Invalid token reference "${ref}": scale "${scaleName}" has no step ${stepStr}.`);
  }
  return entry.hex;
}

function textColor(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return lum > 0.5 ? '#000000' : '#ffffff';
}

function scaleSwatchesHTML(name: string, primitives: PrimitiveTokens): string {
  const scale = primitives[name as ScaleName];
  if (!scale) return '';

  const swatches = SCALE_STEPS.map((step) => {
    const hex = scale[step].hex;
    const fg = textColor(hex);
    return `<div style="background:${hex};color:${fg};padding:8px 12px;font-size:12px;font-family:monospace;display:flex;justify-content:space-between;min-width:140px"><span>${step}</span><span>${hex}</span></div>`;
  }).join('');

  return `<div style="margin-bottom:16px"><h3 style="margin:0 0 4px;font-size:14px;font-family:system-ui">${name}</h3><div style="display:flex;flex-direction:column;border-radius:8px;overflow:hidden">${swatches}</div></div>`;
}

function semanticPairingHTML(
  token: string,
  fgHex: string,
  bgHex: string,
  fgRef: string,
  bgRef: string,
  mode: string
): string {
  const ratio = checkContrast(fgHex, bgHex);
  const pass = ratio >= 4.5;
  const badge = pass
    ? `<span style="color:#16a34a;font-weight:bold">PASS</span>`
    : `<span style="color:#dc2626;font-weight:bold">FAIL</span>`;

  return `<div style="background:${bgHex};color:${fgHex};padding:12px 16px;border-radius:6px;margin-bottom:4px;font-family:monospace;font-size:13px;display:flex;justify-content:space-between;align-items:center"><span>${token} (${mode})</span><span>${ratio.toFixed(2)}:1 ${badge}</span></div>`;
}

export function generateSmokeHTML(
  primitives: PrimitiveTokens,
  semanticMap: SemanticMap,
  themeName: string
): string {
  const scaleNames = Object.keys(primitives) as ScaleName[];
  const scaleSection = scaleNames
    .map((name) => scaleSwatchesHTML(name, primitives))
    .join('');

  const fgTokens = Object.entries(semanticMap).filter(
    ([, entry]) => entry.role === 'fg' && entry.contrastAgainst
  );

  const pairingRows: string[] = [];
  for (const [token, entry] of fgTokens) {
    const bgEntry = semanticMap[entry.contrastAgainst!];
    if (!bgEntry) continue;

    for (const mode of ['light', 'dark'] as const) {
      const fgRef = entry[mode];
      const bgRef = bgEntry[mode];
      const fgHex = resolveHex(fgRef, primitives);
      const bgHex = resolveHex(bgRef, primitives);
      pairingRows.push(
        semanticPairingHTML(token, fgHex, bgHex, fgRef, bgRef, mode)
      );
    }
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${themeName} — Theme Preview</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; padding: 32px; background: #f5f5f5; color: #171717; }
  h1 { margin-bottom: 8px; }
  h2 { margin: 32px 0 16px; border-bottom: 2px solid #e5e5e5; padding-bottom: 8px; }
  .scales { display: flex; flex-wrap: wrap; gap: 16px; }
  .pairings { max-width: 700px; }
</style>
</head>
<body>
<h1>${themeName}</h1>
<p style="color:#737373;margin-bottom:24px">Generated by eluan-theme-generator</p>

<h2>Color Scales</h2>
<div class="scales">${scaleSection}</div>

<h2>Semantic Pairings — Contrast Check</h2>
<div class="pairings">${pairingRows.join('')}</div>
</body>
</html>`;
}
