import { Meta, StoryObj } from '@storybook/react';
import { SearchInput } from './search-input';

declare const meta: Meta<typeof SearchInput>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const WithDebounce: Story;
export declare const Loading: Story;
export declare const CommandPalette: Story;
export declare const CommandPaletteCustomKey: Story;
export declare const Expandable: Story;
export declare const ExpandableCustomWidth: Story;
export declare const Autocomplete: Story;
export declare const AutocompleteWithIcons: Story;
export declare const AutocompleteGrouped: Story;
export declare const AutocompleteMinChars: Story;
export declare const AutocompleteLoading: Story;
export declare const AutocompleteDisabledOptions: Story;
export declare const Disabled: Story;
