import type { Meta, StoryObj } from "@storybook/react"
import { AIWatermark } from "./ai-watermark"

const meta: Meta<typeof AIWatermark> = {
  title: "AI/Trust Builders/AIWatermark",
  component: AIWatermark,
  tags: ["autodocs"],
}

export default meta
type Story = StoryObj<typeof meta>

const sampleContent = (
  <div
    style={{
      padding: "32px",
      background: "#f4f4f5",
      borderRadius: "8px",
      minHeight: "160px",
    }}
  >
    <p style={{ margin: 0 }}>
      This is sample content wrapped by the AI watermark component. It
      demonstrates how the watermark overlays or marks AI-generated content.
    </p>
  </div>
)

const colorBlock = (
  <div
    style={{
      padding: "48px",
      background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
      borderRadius: "8px",
      minHeight: "200px",
      color: "white",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "18px",
      fontWeight: 500,
    }}
  >
    AI-Generated Image Placeholder
  </div>
)

export const Default: Story = {
  render: () => (
    <AIWatermark variant="corner">{sampleContent}</AIWatermark>
  ),
}

export const Overlay: Story = {
  render: () => (
    <AIWatermark variant="overlay">{colorBlock}</AIWatermark>
  ),
}

export const Border: Story = {
  render: () => (
    <AIWatermark variant="border">{sampleContent}</AIWatermark>
  ),
}

export const Positions: Story = {
  render: () => (
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px" }}>
      <AIWatermark variant="corner" position="top-left">
        {sampleContent}
      </AIWatermark>
      <AIWatermark variant="corner" position="top-right">
        {sampleContent}
      </AIWatermark>
      <AIWatermark variant="corner" position="bottom-left">
        {sampleContent}
      </AIWatermark>
      <AIWatermark variant="corner" position="bottom-right">
        {sampleContent}
      </AIWatermark>
    </div>
  ),
}

export const CustomText: Story = {
  render: () => (
    <AIWatermark variant="corner" text="Generated by AI Assistant">
      {sampleContent}
    </AIWatermark>
  ),
}

export const AllVariants: Story = {
  render: () => (
    <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      <AIWatermark variant="corner">{sampleContent}</AIWatermark>
      <AIWatermark variant="overlay">{colorBlock}</AIWatermark>
      <AIWatermark variant="border">{sampleContent}</AIWatermark>
    </div>
  ),
}
