import type { Meta, StoryObj } from "@storybook/react"
import { AIWatermark } from "./ai-watermark"

const meta: Meta<typeof AIWatermark> = {
  title: "Components/AI Watermark",
  component: AIWatermark,
  tags: ["autodocs"],
  parameters: {
    docs: {
      description: {
        component: `
A wrapper component that labels content as AI-generated using a corner badge, diagonal overlay, or dashed border.

**Import**
\`\`\`tsx
import { AIWatermark } from "@vasf/ragnar-core"
\`\`\`

**Usage**
\`\`\`tsx
<AIWatermark variant="corner" position="bottom-right">
  <img src="ai-image.png" alt="AI generated" />
</AIWatermark>
\`\`\`
        `,
      },
    },
  },
}

export default meta
type Story = StoryObj<typeof meta>

const sampleContent = (
  <div
    style={{
      padding: "32px",
      background: "#f4f4f5",
      borderRadius: "8px",
      minHeight: "160px",
    }}
  >
    <p style={{ margin: 0 }}>
      This is sample content wrapped by the AI watermark component. It
      demonstrates how the watermark overlays or marks AI-generated content.
    </p>
  </div>
)

const colorBlock = (
  <div
    style={{
      padding: "48px",
      background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
      borderRadius: "8px",
      minHeight: "200px",
      color: "white",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: "18px",
      fontWeight: 500,
    }}
  >
    AI-Generated Image Placeholder
  </div>
)

export const Default: Story = {
  parameters: {
    docs: {
      description: {
        story: "Corner variant with a small badge positioned at bottom-right by default.",
      },
    },
  },
  render: () => (
    <AIWatermark variant="corner">{sampleContent}</AIWatermark>
  ),
}

export const Overlay: Story = {
  parameters: {
    docs: {
      description: {
        story: "Overlay variant that renders a diagonal translucent watermark text across the content.",
      },
    },
  },
  render: () => (
    <AIWatermark variant="overlay">{colorBlock}</AIWatermark>
  ),
}

export const Border: Story = {
  parameters: {
    docs: {
      description: {
        story: "Border variant that wraps content with a dashed border and a badge.",
      },
    },
  },
  render: () => (
    <AIWatermark variant="border">{sampleContent}</AIWatermark>
  ),
}

export const Positions: Story = {
  parameters: {
    docs: {
      description: {
        story: "Shows the four position options: top-left, top-right, bottom-left, and bottom-right.",
      },
    },
  },
  render: () => (
    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px" }}>
      <AIWatermark variant="corner" position="top-left">
        {sampleContent}
      </AIWatermark>
      <AIWatermark variant="corner" position="top-right">
        {sampleContent}
      </AIWatermark>
      <AIWatermark variant="corner" position="bottom-left">
        {sampleContent}
      </AIWatermark>
      <AIWatermark variant="corner" position="bottom-right">
        {sampleContent}
      </AIWatermark>
    </div>
  ),
}

export const CustomText: Story = {
  parameters: {
    docs: {
      description: {
        story: "Corner variant with custom watermark text instead of the default 'AI Generated'.",
      },
    },
  },
  render: () => (
    <AIWatermark variant="corner" text="Generated by AI Assistant">
      {sampleContent}
    </AIWatermark>
  ),
}

export const AllVariants: Story = {
  parameters: {
    docs: {
      description: {
        story: "Side-by-side comparison of all three variants: corner, overlay, and border.",
      },
    },
  },
  render: () => (
    <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      <AIWatermark variant="corner">{sampleContent}</AIWatermark>
      <AIWatermark variant="overlay">{colorBlock}</AIWatermark>
      <AIWatermark variant="border">{sampleContent}</AIWatermark>
    </div>
  ),
}
